import { Leaf } from "lucide-react";

const Terms = () => {
  return (
    <div className="min-h-screen py-20 relative z-10 w-full max-w-4xl mx-auto px-6">
      <div className="mb-12">
        <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full border border-primary/30 bg-primary/10 text-primary font-medium text-sm mb-6 shadow-[var(--shadow-glow)]">
          <Leaf className="w-4 h-4" />
          <span>Legal</span>
        </div>
        <h1 className="text-4xl md:text-5xl font-heading font-extrabold mb-4 gradient-text">
          Terms & Conditions
        </h1>
        <p className="text-muted-foreground">Last updated: {new Date().toLocaleDateString()}</p>
      </div>

      <div className="glass-card p-8 md:p-12 space-y-8 text-foreground/80 leading-relaxed">
        <section>
          <h2 className="text-2xl font-bold font-heading mb-4 text-white">1. Acceptance of Terms</h2>
          <p>
            By accessing and using the GreenVerse platform, connecting your Web3 wallet, or minting any GreenVerse NFTs, you agree to comply with and be bound by these Terms and Conditions. If you do not agree, please do not use our services.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-bold font-heading mb-4 text-white">2. NFTs and Blockchain Transactions</h2>
          <p className="mb-4">
            GreenVerse operates as a decentralized marketplace where users can mint digital assets ("NFTs") on the blockchain. You acknowledge that:
          </p>
          <ul className="list-disc pl-6 space-y-2">
            <li>Transactions utilize smart contracts and are irreversible once confirmed on the blockchain.</li>
            <li>GreenVerse takes no responsibility for failed transactions, lost gas fees, or user errors when sending funds.</li>
            <li>The value of cryptocurrencies is highly volatile. The mint price in local fiat may fluctuate significantly.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-2xl font-bold font-heading mb-4 text-white">3. Direct Funding Model</h2>
          <p>
            GreenVerse utilizes a direct funding model. When you click "Pay & Mint", your funds are routed directly from your wallet to the associated foundation or treasury wallet without intermediation. Your NFT acts as a digital receipt of this transaction and does not constitute a financial investment, security, or share in any enterprise.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-bold font-heading mb-4 text-white">4. User Responsibility</h2>
          <p>
            You are entirely responsible for the safety and management of your own private Web3 wallets and validating all transactions and contracts generated by this website before approval. Always verify the transaction details inside your MetaMask extension before signing.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-bold font-heading mb-4 text-white">5. Intellectual Property</h2>
          <p>
            The 3D tree assets, interface designs, copy, and code belonging to GreenVerse are protected intellectual property. Minting a GreenVerse NFT grants you a personal, non-commercial license to display the art associated with your specific token. It does not grant you the right to utilize the artwork for commercial branding, marketing, or resale outside of secondary NFT marketplaces.
          </p>
        </section>
      </div>
    </div>
  );
};

export default Terms;
